### PR TITLE
Revert "Gui System"

### PR DESCRIPTION
**Pull request by axlecoffee**
Reverts SkyBlock-Central/SkyBlock-Core#10

### CODE REVIEW

**Comment by KyllianGamer** [comment]
lgtm


(Let's Gamble, Try Merging)

**Review by DuckySoLucky — APPROVED** [review]
let's gamble, try merging!

**Comment by axlecoffee** [comment]
nah bro not doin this again

**Comment by KyllianGamer** [comment]
> nah bro not doin this again

Man gets the chance to fix his mistake and says "nah"

**Comment by DuckySoLucky** [comment]
> > nah bro not doin this again
> 
> Man gets the chance to fix his mistake and says "nah"

fr

**Comment by axlecoffee** [comment]
> > > nah bro not doin this again
> > 
> > 
> > Man gets the chance to fix his mistake and says "nah"
> 
> fr

you fr say "fr" when you yell at me for merging ANYTHING

**Pull request merged**
