### PR TITLE
Update build.yml to ignore files that don't impact builds

### PR DESCRIPTION
**Pull request by Ascynx**
(wait till action runs to see if I didn't break it)

### CODE REVIEW

**Comment by Ascynx** [comment]
I did

**Comment by TGWaffles** [comment]
Maybe just remove all files ending with .md?

**Comment by Ascynx** [comment]
> Maybe just remove all files ending with .md?

prolly yeah

**Comment by Ascynx** [comment]
honestly would've probably been smarter to use "paths:" and match files in src along with the gradle files instead of using "paths-ignore"

**Comment by Harry282** [comment]
any reason why push and pull request are separate?

**Comment by Ascynx** [comment]
> any reason why push and pull request are separate?

I don't think you can do
```yml
on: [push, pull_request]
    paths-ignore:
```

**Review by CraftedFury — APPROVED** [review]

**Review by axlecoffee — APPROVED** [review]

**Pull request merged**
